[package]
name = "http-server"
version = "0.1.0"
authors = ["Esteban Borai <estebanborai@gmail.com>"]
edition = "2018"
description = "Simple and configurable command-line HTTP server"
repository = "https://github.com/EstebanBorai/http-server"
categories = ["web-programming", "web-programming::http-server"]
keywords = ["configurable", "http", "server", "serve", "static"]
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-stream = "0.3"
chrono = "0.4"
clap = "2"
futures = "0.3"
http = "0.2"
handlebars = "3"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = "0.22"
hyper-staticfile = "0.6"
rustls = "0.19"
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.22"
toml = "0.5"
serde = { version = "1", features = ["derive"] }
